Feature/agrega funcionalidad a query
IslasGECI/queries pull request #12
Opened 2020-12-16 21:43 UTC by MaritzaB

Listo @islasfernando , ya modifiqué el query.
Le podemos decir las columnas que queremos por fuera. Creo que algo que falta arreglar en los repos dónde se instalará este query es uniformizar el nombre de los campos del archivo de entrada. En los repos tenemos campos que difieren de nombre, por ejemplo: `p_value` en uno y en otro `p_valor`.

2021-01-20 20:18 UTC, xwalls commented
Hola @MaritzaB, en que puedo ayudarte a revisar aquí?

2021-01-28 21:45 UTC, MaritzaB commented
Hola @xwalls, tenemos que lograr instalar [esta función](src/select_growth_rates_and_p_values) en el repo de `lambdas_aves_marinas` para verificar que sigue funcionando en ese repo.
Si efectivamente funciona, entonces creo que podríamos cerrar este _PR_ 😉.

2021-03-16 20:32 UTC, evaristor commented
🙌🏾  El `make test` sí pasa:
```
make tests
```
```
mkdir --parents /usr/local/bin
cp ./src/* /usr/local/bin
chmod +x /usr/local/bin/*
export PATH="/usr/local/bin:${PATH}"
# Doctest:
mkdir --parents /usr/local/doctests
cp ./tests/test_*.py /usr/local/doctests
[ $(tail -1 tests/data/test_2019-2020.csv | cut --characters=1-11) == "01/Dic/2019" ] && \
    [ $(cambia_formato_fecha tests/data/test_2019-2020.csv | tail -1 | cut --characters=1-10) == "2019-12-01" ]
bats tests/bats_tests/test_select_growth_rates_and_p_values.sh
 ✓ select_growth_rates_and_p_values_cormorant
 ✓ select_growth_rates_and_p_values_regional_seabirds
 ✓ select_growth_rates_and_p_values_seabirds

3 tests, 0 failures
```

2021-03-16 20:39 UTC, evaristor commented
@MaritzaB No me queda muy claro que debo hacer para revisar este PR. En el repo de *lambdas_aves_marinas*, ¿debo sustituir el llamado al _script_ `src/query_growth_rates_and_p_values` por el _script_ equivalente en este repo *queries*?

¿Por favor podrías agregar un _checklist_ a la descripción de este PR?

2021-03-16 20:54 UTC, evaristor requested changes
Logré instalar este repo en el repo `lambdas_aves_marinas`, pero no supe como usar el _script_ instalado `select_growth_rates_and_p_values`.

¿Por favor me podrías explicar (en la descripción de este PR) que comando debo correr (cómo debo ejecutar `select_growth_rates_and_p_values`) para verificar que su funcionamiento es correcto?

2021-04-15 19:53 UTC, MaritzaB commented
Para revisar este PR hay que verificar que el query que refactorizamos en este repositorio sigue funcionando en el repo de `lambdas_aves_marinas` y en el de `cormorant_population_growth`.
[En este PR](https://bitbucket.org/IslasGECI/lambdas_aves_marinas/pull-requests/27/release-refactoriza-funcion) podemos verificar que ya está instalado en `lambdas_aves_marinas` y que no se rompió el reporte.

2021-04-15 20:54 UTC, evaristor approved these changes
💯👍😄

2021-04-15 20:54 UTC, merged