Agrega script para correr queries en sqlite
IslasGECI/queries pull request #20
Opened 2021-05-04 19:48 UTC by MaritzaB

Agregué el script `run_query` para que podamos tener por separado los queries en un archivo `.sql` y ejecutarlos con sqlite con `run_query`.

2021-05-04 20:07 UTC, evaristor commented on Makefile
> +tests: install bats_tests
¡Me gustó este cambio!

2021-05-04 20:07 UTC, evaristor commented on Makefile
> +bats_tests:
¡Me gustó este cambio!

2021-05-05 16:25 UTC, evaristor requested changes
Me emociona mucho este _script_. Es un paso en la dirección correcta. Felicidades.

2021-05-05 16:25 UTC, evaristor commented on src/run_query
> +query_name=$(basename "${sql_query}" .sql)
¿Por que usas el export en `table_name` pero no en `query_name`?

2021-05-05 16:25 UTC, evaristor commented on src/run_query
> +data_file=${2}
Me gusta la simetría entre `query_name` y `table_name`. ¿Podríamos tener algo similar aquí? Por ejemplo `query_file` y `data_file` o `query_path` y `data_path`

2021-05-05 18:10 UTC, MaritzaB commented on src/run_query
> +query_name=$(basename "${sql_query}" .sql)
Ah, lo que pasa es que exportamos el `table_name` porque el nombre de la tabla lo utilizamos en los queries que vamos a correr, es decir en los archivos `.sql`.
Por ejemplo, en el query vamos a tener algo así:
```
SELECT *
FROM '${table_name}'
```

Con el `query_name` es diferente porque no necesitamos exportarlo, dado que lo utilizamos aquí en el mismo script.

¿No sé si me di a entender 😅 ?

2021-05-05 18:12 UTC, MaritzaB commented on src/run_query
> +data_file=${2}
Listo 🙌🏽

2021-05-12 02:14 UTC, evaristor approved these changes
💯 😃

2021-05-12 02:15 UTC, merged