Feature/agrega query catch and effort per year
IslasGECI/queries pull request #9
Opened 2020-07-23 20:59 UTC by MaritzaB

Agrega query que cuenta el esfuerzo y capturas de gatos guadalupe

2020-07-27 22:23 UTC, evaristor commented
@MaritzaB ¿Está en el renglón de [**Implementación**](https://github.com/IslasGECI/manual#implementaci%C3%B3n-en-bash)?

2020-08-17 17:01 UTC, nepito commented on src/catch_and_effort_per_year
> +#!/usr/bin/env bash
por favor divide esta función en tres. Tal vez podrían ser `get_captures_by_zone`, `get_effort_by_zone` y `effort_captures_by_zone`

2020-08-17 17:04 UTC, nepito commented on src/catch_and_effort_per_year
> +csvsql --snifflimit 0 --no-inference --blanks --query \
esta linea se repite en la 20 y en la 34, tal vez sea posible refactorizarla si los _queries_ se SQL están a parte

2020-08-17 17:08 UTC, nepito commented on src/catch_and_effort_per_year
> +csvsql --snifflimit 0 --no-inference --blanks --query \
de las 13 líneas que hay en esta función se repiten 10 (77%) y las otras tres tienen formas muy parecidas:
`${first_file} > Capturas.csv;` y ` ${first_file} > Esfuerzos.csv` 
`WHERE Estado_trampa = 'X' OR Estado_trampa = 'A'` y `WHERE Estado_trampa = 'X'`
`COUNT(*) AS Capturas` y `COUNT(*) AS Esfuerzo`
Creo que tiene potencial para refactorizarse

2020-09-10 16:06 UTC, evaristor requested changes

2020-09-10 16:06 UTC, evaristor commented on src/catch_and_effort_per_year
> +
Aquí inicia otro bloque de código. Por favor podrías agregar un comentario explicando que hace el siguiente bloque de código?

2020-09-10 16:06 UTC, evaristor commented on src/catch_and_effort_per_year
> +
Aquí inicia otro bloque de código. Por favor podrías agregar un comentario explicando que hace el siguiente bloque de código?

2020-09-24 22:09 UTC, MaritzaB commented
Hola @evaristor y @nepito . Muchas gracias por su revisión. La función original que estaba en revisión ya es obsoleta. En su lugar implemente algunas funciones para hacer el resumen semanal del archivo de `ig_posicion_trampas_gatos`. 
Las funciones que implementé son las siguientes:

`change_header`
`remove_rows_with_specific_text`
`get_captures_by_zone`
`get_effort_by_zone`
`join_effort_and_captures_files`
`effort_captures_by_zone`

Las funciones `get_captures_by_zone` y `get_effort_by_zone` son queries con los que se obtienen las capturas y el esfuerzo del archivo.
Con el archivo `join_effort_and_captures_files` unimos las tablas que obtuvimos con las funciones anteriores.
Y con `effort_captures_by_zone` unimos todas las funciones anteriores.
Hasta ahorita solo tiene prueba la de `effort_captures_by_zone` en doctest.

2020-09-29 19:44 UTC, evaristor requested changes
¿Por favor podrías describir cada _script_ en un comentario de una línea?

2020-09-29 19:44 UTC, evaristor commented on src/effort_captures_by_zone
> +#
Por favor podrias agregar una descripción de una línea?

2020-09-29 19:44 UTC, evaristor commented on src/get_captures_by_zone
> +#
Por favor podrías agregar una descripción de una línea?

2020-09-29 19:44 UTC, evaristor commented on src/get_effort_by_zone
> +#
Por favor podrías agregar una descripción de una línea?

2020-09-29 19:44 UTC, evaristor commented on src/join_effort_and_captures_files
> +#
Por favor podrías agregar una descripción de una línea?

2020-09-29 19:44 UTC, evaristor commented on src/remove_rows_with_specific_text
> +#
Por favor podrías agregar una descripción de una línea?

2020-10-12 20:21 UTC, MaritzaB commented
Hola @evaristor y @nepito:
Mude las funciones de este Pull Request al repo de [`datatools`](https://github.com/IslasGECI/datatools/pull/4), ya que era más adecuado para esta función que hace el resumen semanal de gatos del archivo de `posicion_trampas`. Las correcciones que me hicieron en este PR ya las implementé en el [nuevo PR](https://github.com/IslasGECI/datatools/pull/4).

2020-10-13 19:22 UTC, merged